export const COUNTRIES = [
  { label: "Germany", value: "de" },
  { label: "Brazil", value: "br" },
  { label: "United States", value: "us" },
  { label: "France", value: "fr" },
  { label: "China", value: "cn" },
  { label: "India", value: "in" },
  { label: "Japan", value: "jp" },
  { label: "Canada", value: "ca" },
  { label: "United Kingdom", value: "uk" },
  { label: "Italy", value: "it" },
  { label: "Australia", value: "au" },
  { label: "Spain", value: "es" },
  { label: "Mexico", value: "mx" },
  { label: "South Korea", value: "kr" },
  { label: "Russia", value: "ru" },
  { label: "Netherlands", value: "nl" },
  { label: "Switzerland", value: "ch" },
  { label: "Sweden", value: "se" },
  { label: "Norway", value: "no" },
  { label: "Denmark", value: "dk" },
  { label: "Finland", value: "fi" },
  { label: "Portugal", value: "pt" },
  { label: "Argentina", value: "ar" },
  { label: "Turkey", value: "tr" },
  { label: "Belgium", value: "be" },
  { label: "Austria", value: "at" },
  { label: "Poland", value: "pl" },
  { label: "South Africa", value: "za" },
  { label: "Singapore", value: "sg" },
  { label: "New Zealand", value: "nz" },
  { label: "Ireland", value: "ie" },
  { label: "Greece", value: "gr" },
  { label: "Chile", value: "cl" },
  { label: "Colombia", value: "co" },
  { label: "Peru", value: "pe" },
  { label: "Malaysia", value: "my" },
  { label: "Philippines", value: "ph" },
  { label: "Thailand", value: "th" },
  { label: "Vietnam", value: "vn" },
  { label: "Egypt", value: "eg" },
  { label: "Saudi Arabia", value: "sa" },
  { label: "United Arab Emirates", value: "ae" },
  { label: "Nigeria", value: "ng" },
  { label: "Kenya", value: "ke" },
  { label: "Morocco", value: "ma" },
  { label: "Israel", value: "il" },
  { label: "Pakistan", value: "pk" },
  { label: "Bangladesh", value: "bd" },
  { label: "Indonesia", value: "id" },
  { label: "Iran", value: "ir" },
  { label: "Iraq", value: "iq" },
  { label: "Lebanon", value: "lb" },
  { label: "Jordan", value: "jo" },
  { label: "Qatar", value: "qa" },
  { label: "Kuwait", value: "kw" },
  { label: "Oman", value: "om" },
  { label: "Bahrain", value: "bh" },
  { label: "Cyprus", value: "cy" },
  { label: "Estonia", value: "ee" },
  { label: "Latvia", value: "lv" },
  { label: "Lithuania", value: "lt" },
  { label: "Czech Republic", value: "cz" },
  { label: "Slovakia", value: "sk" },
  { label: "Hungary", value: "hu" },
  { label: "Romania", value: "ro" },
  { label: "Bulgaria", value: "bg" },
  { label: "Croatia", value: "hr" },
  { label: "Slovenia", value: "si" },
  { label: "Bosnia and Herzegovina", value: "ba" },
  { label: "Montenegro", value: "me" },
  { label: "North Macedonia", value: "mk" },
  { label: "Serbia", value: "rs" },
  { label: "Albania", value: "al" },
  { label: "Kosovo", value: "xk" },
  { label: "Ukraine", value: "ua" },
  { label: "Belarus", value: "by" },
  { label: "Moldova", value: "md" },
  { label: "Georgia", value: "ge" },
  { label: "Armenia", value: "am" },
  { label: "Azerbaijan", value: "az" },
  { label: "Kazakhstan", value: "kz" },
  { label: "Uzbekistan", value: "uz" },
  { label: "Turkmenistan", value: "tm" },
  { label: "Kyrgyzstan", value: "kg" },
  { label: "Tajikistan", value: "tj" },
  { label: "Afghanistan", value: "af" },
]
